// GENERATED FILE — do not hand-edit.
// Rewritten by `npm run validate:starters -- --write`, which also fails the
// run when this file has drifted from `items/`.
//
// The picker needs id/title/difficulty/topic/summary and nothing else. Keeping
// that in its own literal is what lets /start list every problem without the
// prompts and 5 starters apiece riding along in the client bundle.

import type { ProblemMeta } from "./types";

export const PROBLEM_CATALOG: ProblemMeta[] = [
  {
    id: "best-time-to-buy-and-sell-stock",
    title: "Best Time to Buy and Sell Stock",
    difficulty: "Easy",
    topic: "Array",
    summary: "Buy once and sell later for the largest possible profit.",
  },
  {
    id: "contains-duplicate",
    title: "Contains Duplicate",
    difficulty: "Easy",
    topic: "Array",
    summary: "Decide whether any value appears more than once.",
  },
  {
    id: "two-sum",
    title: "Two Sum",
    difficulty: "Easy",
    topic: "Array",
    summary: "Find the two indices whose values add up to a target.",
  },
  {
    id: "three-sum",
    title: "3Sum",
    difficulty: "Medium",
    topic: "Array",
    summary: "Find every unique triple that sums to zero.",
  },
  {
    id: "container-with-most-water",
    title: "Container With Most Water",
    difficulty: "Medium",
    topic: "Array",
    summary: "Pick two lines that hold the most water between them.",
  },
  {
    id: "maximum-product-subarray",
    title: "Maximum Product Subarray",
    difficulty: "Medium",
    topic: "Array",
    summary: "Find the contiguous run with the largest product.",
  },
  {
    id: "maximum-subarray",
    title: "Maximum Subarray",
    difficulty: "Medium",
    topic: "Array",
    summary: "Find the contiguous run with the largest sum.",
  },
  {
    id: "product-of-array-except-self",
    title: "Product of Array Except Self",
    difficulty: "Medium",
    topic: "Array",
    summary: "Build the products of every element except the current one.",
  },
  {
    id: "valid-anagram",
    title: "Valid Anagram",
    difficulty: "Easy",
    topic: "String",
    summary: "Check whether one string is a rearrangement of another.",
  },
  {
    id: "valid-palindrome",
    title: "Valid Palindrome",
    difficulty: "Easy",
    topic: "String",
    summary: "Check for a palindrome, ignoring case and punctuation.",
  },
  {
    id: "valid-parentheses",
    title: "Valid Parentheses",
    difficulty: "Easy",
    topic: "String",
    summary: "Decide whether a string of brackets is properly nested.",
  },
  {
    id: "encode-and-decode-strings",
    title: "Encode and Decode Strings",
    difficulty: "Medium",
    topic: "String",
    summary: "Serialise a list of strings so it can be recovered exactly.",
  },
  {
    id: "group-anagrams",
    title: "Group Anagrams",
    difficulty: "Medium",
    topic: "String",
    summary: "Bucket words together when they share the same letters.",
  },
  {
    id: "longest-palindromic-substring",
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    topic: "String",
    summary: "Return the longest substring that reads the same both ways.",
  },
  {
    id: "longest-repeating-character-replacement",
    title: "Longest Repeating Character Replacement",
    difficulty: "Medium",
    topic: "String",
    summary: "Grow the longest single-letter run using k replacements.",
  },
  {
    id: "longest-substring-without-repeating-characters",
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    topic: "String",
    summary: "Measure the longest window with no repeated character.",
  },
  {
    id: "palindromic-substrings",
    title: "Palindromic Substrings",
    difficulty: "Medium",
    topic: "String",
    summary: "Count every palindromic substring, including single letters.",
  },
  {
    id: "minimum-window-substring",
    title: "Minimum Window Substring",
    difficulty: "Hard",
    topic: "String",
    summary: "Find the shortest window covering every character of a pattern.",
  },
  {
    id: "counting-bits",
    title: "Counting Bits",
    difficulty: "Easy",
    topic: "Binary",
    summary: "Count the set bits of every number from 0 to n.",
  },
  {
    id: "missing-number",
    title: "Missing Number",
    difficulty: "Easy",
    topic: "Binary",
    summary: "Find the one value missing from 0..n.",
  },
  {
    id: "number-of-1-bits",
    title: "Number of 1 Bits",
    difficulty: "Easy",
    topic: "Binary",
    summary: "Count the set bits in an unsigned 32-bit integer.",
  },
  {
    id: "reverse-bits",
    title: "Reverse Bits",
    difficulty: "Easy",
    topic: "Binary",
    summary: "Reverse the 32 bits of an unsigned integer.",
  },
  {
    id: "find-minimum-in-rotated-sorted-array",
    title: "Find Minimum in Rotated Sorted Array",
    difficulty: "Medium",
    topic: "Binary",
    summary: "Locate the smallest value in a sorted array that has been rotated.",
  },
  {
    id: "search-in-rotated-sorted-array",
    title: "Search in Rotated Sorted Array",
    difficulty: "Medium",
    topic: "Binary",
    summary: "Binary-search a sorted array that has been rotated at an unknown pivot.",
  },
  {
    id: "sum-of-two-integers",
    title: "Sum of Two Integers",
    difficulty: "Medium",
    topic: "Binary",
    summary: "Add two numbers without using + or -.",
  },
  {
    id: "climbing-stairs",
    title: "Climbing Stairs",
    difficulty: "Easy",
    topic: "Dynamic Programming",
    summary: "Count the ways to climb n steps taking 1 or 2 at a time.",
  },
  {
    id: "coin-change",
    title: "Coin Change",
    difficulty: "Medium",
    topic: "Dynamic Programming",
    summary: "Make an amount with the fewest coins.",
  },
  {
    id: "combination-sum",
    title: "Combination Sum",
    difficulty: "Medium",
    topic: "Dynamic Programming",
    summary: "List every multiset of candidates hitting a target.",
  },
  {
    id: "decode-ways",
    title: "Decode Ways",
    difficulty: "Medium",
    topic: "Dynamic Programming",
    summary: "Count the readings of a digit string as A–Z.",
  },
  {
    id: "house-robber",
    title: "House Robber",
    difficulty: "Medium",
    topic: "Dynamic Programming",
    summary: "Take the most money without robbing adjacent houses.",
  },
  {
    id: "house-robber-ii",
    title: "House Robber II",
    difficulty: "Medium",
    topic: "Dynamic Programming",
    summary: "Same rules, but the street is a circle.",
  },
  {
    id: "jump-game",
    title: "Jump Game",
    difficulty: "Medium",
    topic: "Dynamic Programming",
    summary: "Decide whether you can reach the end of the array.",
  },
  {
    id: "longest-common-subsequence",
    title: "Longest Common Subsequence",
    difficulty: "Medium",
    topic: "Dynamic Programming",
    summary: "Measure the longest subsequence shared by two strings.",
  },
  {
    id: "longest-increasing-subsequence",
    title: "Longest Increasing Subsequence",
    difficulty: "Medium",
    topic: "Dynamic Programming",
    summary: "Measure the longest strictly increasing subsequence.",
  },
  {
    id: "unique-paths",
    title: "Unique Paths",
    difficulty: "Medium",
    topic: "Dynamic Programming",
    summary: "Count the routes across a grid moving only right and down.",
  },
  {
    id: "word-break",
    title: "Word Break",
    difficulty: "Medium",
    topic: "Dynamic Programming",
    summary: "Decide whether a string splits into dictionary words.",
  },
  {
    id: "meeting-rooms",
    title: "Meeting Rooms",
    difficulty: "Easy",
    topic: "Interval",
    summary: "Decide whether one person can attend every meeting.",
  },
  {
    id: "insert-interval",
    title: "Insert Interval",
    difficulty: "Medium",
    topic: "Interval",
    summary: "Slot a new interval into a sorted list, merging as needed.",
  },
  {
    id: "meeting-rooms-ii",
    title: "Meeting Rooms II",
    difficulty: "Medium",
    topic: "Interval",
    summary: "Count the fewest rooms that fit every meeting.",
  },
  {
    id: "merge-intervals",
    title: "Merge Intervals",
    difficulty: "Medium",
    topic: "Interval",
    summary: "Collapse a set of overlapping intervals into the minimal set.",
  },
  {
    id: "non-overlapping-intervals",
    title: "Non-overlapping Intervals",
    difficulty: "Medium",
    topic: "Interval",
    summary: "Remove as few intervals as possible to kill all overlaps.",
  },
  {
    id: "linked-list-cycle",
    title: "Linked List Cycle",
    difficulty: "Easy",
    topic: "Linked List",
    summary: "Detect whether a linked list loops back on itself.",
  },
  {
    id: "merge-two-sorted-lists",
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    topic: "Linked List",
    summary: "Splice two sorted lists into one sorted list.",
  },
  {
    id: "reverse-linked-list",
    title: "Reverse Linked List",
    difficulty: "Easy",
    topic: "Linked List",
    summary: "Flip the direction of every pointer in a singly linked list.",
  },
  {
    id: "remove-nth-node-from-end-of-list",
    title: "Remove Nth Node From End of List",
    difficulty: "Medium",
    topic: "Linked List",
    summary: "Drop the nth node counting back from the tail.",
  },
  {
    id: "reorder-list",
    title: "Reorder List",
    difficulty: "Medium",
    topic: "Linked List",
    summary: "Interleave a list's front and back halves in place.",
  },
  {
    id: "merge-k-sorted-lists",
    title: "Merge k Sorted Lists",
    difficulty: "Hard",
    topic: "Linked List",
    summary: "Merge an array of sorted lists into one sorted list.",
  },
  {
    id: "rotate-image",
    title: "Rotate Image",
    difficulty: "Medium",
    topic: "Matrix",
    summary: "Turn a square matrix 90 degrees clockwise, in place.",
  },
  {
    id: "set-matrix-zeroes",
    title: "Set Matrix Zeroes",
    difficulty: "Medium",
    topic: "Matrix",
    summary: "Blank out the row and column of every zero, in place.",
  },
  {
    id: "spiral-matrix",
    title: "Spiral Matrix",
    difficulty: "Medium",
    topic: "Matrix",
    summary: "Read a matrix in clockwise spiral order.",
  },
  {
    id: "word-search",
    title: "Word Search",
    difficulty: "Medium",
    topic: "Matrix",
    summary: "Trace a word through adjacent cells of a letter grid.",
  },
  {
    id: "invert-binary-tree",
    title: "Invert Binary Tree",
    difficulty: "Easy",
    topic: "Tree",
    summary: "Mirror a binary tree by swapping every pair of children.",
  },
  {
    id: "maximum-depth-of-binary-tree",
    title: "Maximum Depth of Binary Tree",
    difficulty: "Easy",
    topic: "Tree",
    summary: "Measure the longest root-to-leaf path.",
  },
  {
    id: "same-tree",
    title: "Same Tree",
    difficulty: "Easy",
    topic: "Tree",
    summary: "Decide whether two binary trees are structurally identical.",
  },
  {
    id: "subtree-of-another-tree",
    title: "Subtree of Another Tree",
    difficulty: "Easy",
    topic: "Tree",
    summary: "Check whether one tree appears intact inside another.",
  },
  {
    id: "add-and-search-word",
    title: "Add and Search Word",
    difficulty: "Medium",
    topic: "Tree",
    summary: "A dictionary where '.' matches any single letter.",
  },
  {
    id: "binary-tree-level-order-traversal",
    title: "Binary Tree Level Order Traversal",
    difficulty: "Medium",
    topic: "Tree",
    summary: "Return the node values one level at a time.",
  },
  {
    id: "construct-binary-tree-from-preorder-and-inorder",
    title: "Construct Binary Tree from Preorder and Inorder Traversal",
    difficulty: "Medium",
    topic: "Tree",
    summary: "Rebuild a tree from its preorder and inorder traversals.",
  },
  {
    id: "implement-trie-prefix-tree",
    title: "Implement Trie (Prefix Tree)",
    difficulty: "Medium",
    topic: "Tree",
    summary: "Build a prefix tree supporting insert, search and startsWith.",
  },
  {
    id: "kth-smallest-element-in-a-bst",
    title: "Kth Smallest Element in a BST",
    difficulty: "Medium",
    topic: "Tree",
    summary: "Find the kth smallest value in a binary search tree.",
  },
  {
    id: "lowest-common-ancestor-of-a-bst",
    title: "Lowest Common Ancestor of a BST",
    difficulty: "Medium",
    topic: "Tree",
    summary: "Find the deepest node that has both targets below it.",
  },
  {
    id: "validate-binary-search-tree",
    title: "Validate Binary Search Tree",
    difficulty: "Medium",
    topic: "Tree",
    summary: "Verify that a tree satisfies the BST ordering everywhere.",
  },
  {
    id: "binary-tree-maximum-path-sum",
    title: "Binary Tree Maximum Path Sum",
    difficulty: "Hard",
    topic: "Tree",
    summary: "Find the highest-scoring path anywhere in the tree.",
  },
  {
    id: "serialize-and-deserialize-binary-tree",
    title: "Serialize and Deserialize Binary Tree",
    difficulty: "Hard",
    topic: "Tree",
    summary: "Turn a tree into a string and rebuild it exactly.",
  },
  {
    id: "word-search-ii",
    title: "Word Search II",
    difficulty: "Hard",
    topic: "Tree",
    summary: "Find every dictionary word hidden in a letter grid.",
  },
  {
    id: "clone-graph",
    title: "Clone Graph",
    difficulty: "Medium",
    topic: "Graph",
    summary: "Deep-copy a connected undirected graph.",
  },
  {
    id: "course-schedule",
    title: "Course Schedule",
    difficulty: "Medium",
    topic: "Graph",
    summary: "Decide whether prerequisites allow finishing every course.",
  },
  {
    id: "graph-valid-tree",
    title: "Graph Valid Tree",
    difficulty: "Medium",
    topic: "Graph",
    summary: "Check whether an undirected graph is exactly a tree.",
  },
  {
    id: "longest-consecutive-sequence",
    title: "Longest Consecutive Sequence",
    difficulty: "Medium",
    topic: "Graph",
    summary: "Find the longest run of consecutive integers in any order.",
  },
  {
    id: "number-of-connected-components",
    title: "Number of Connected Components in an Undirected Graph",
    difficulty: "Medium",
    topic: "Graph",
    summary: "Count the separate pieces of an undirected graph.",
  },
  {
    id: "number-of-islands",
    title: "Number of Islands",
    difficulty: "Medium",
    topic: "Graph",
    summary: "Count connected regions of land in a grid.",
  },
  {
    id: "pacific-atlantic-water-flow",
    title: "Pacific Atlantic Water Flow",
    difficulty: "Medium",
    topic: "Graph",
    summary: "Find cells that drain to both oceans.",
  },
  {
    id: "alien-dictionary",
    title: "Alien Dictionary",
    difficulty: "Hard",
    topic: "Graph",
    summary: "Recover a letter ordering from a sorted word list.",
  },
  {
    id: "top-k-frequent-elements",
    title: "Top K Frequent Elements",
    difficulty: "Medium",
    topic: "Heap",
    summary: "Return the k values that appear most often.",
  },
  {
    id: "find-median-from-data-stream",
    title: "Find Median from Data Stream",
    difficulty: "Hard",
    topic: "Heap",
    summary: "Keep a running median as numbers arrive one at a time.",
  },
  {
    id: "lru-cache",
    title: "LRU Cache",
    difficulty: "Hard",
    topic: "Design",
    summary: "Design a cache that evicts the least-recently-used entry.",
  },
];

const BY_ID = new Map(PROBLEM_CATALOG.map((p) => [p.id, p]));

export function getProblemMeta(id: string | null | undefined): ProblemMeta | undefined {
  return id ? BY_ID.get(id) : undefined;
}
